# The URL the site will be built for
base_url = "/"
title = "blo(c)k"
description = "Personal blog of someone named anins1der's; about tech, programming, and other shit."

theme = "ametrine"
author = "anins1der"

compile_sass = true
build_search_index = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

# Based on https://github.com/welpo/tabi

# To translate the entire theme, there must be a file with the same ISO 639-1
# or BCP 47 language code in the "i18n" directory of your site or the Ametrine
# theme, for example, "i18n/fr.toml" for French or "i18n/zh-Hans.toml" for
# Simplified Chinese, otherwise the theme will be in English.

# ISO 639-1: https://localizely.com/iso-639-1-list/
# BCP 47: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
default_language = "en"

taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
  { name = "categories", feed = true },
]

[markdown]
smart_punctuation = true
bottom_footnotes = true
external_links_class = "external"
github_alerts = true
insert_anchor_links = "left"

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised by customizing stuff below.
style = "class"
light_theme = "monokai-pro-light"
dark_theme = "monokai-pro"
extra_themes = [
  "themes/ametrine/giallo/themes/monokai-pro-light.json",
  "themes/ametrine/giallo/themes/monokai-pro.json",
]

[search]
# Accepted values are "elasticlunr_javascript" and "elasticlunr_json"
index_format = "elasticlunr_json"

[link_checker]
internal_level = "warn"

[extra]
# Usage of an icon is heavily adviced. In case if none is provided, a question
# mark icon will be used instead.
# Any icon name from https://phosphoricons.com can be used.
# Color attribute accepts the same values as extra.accent_color, which can be
# found below.
categories = [
  { name = "Archived", description = "Posts that have been archived due to their age.", color = "purple", icon = "box-arrow-down" },
  { name = "Featured", description = "Posts that are somewhat decently written.", color = "yellow", icon = "star" },
  { name = "Hot", description = "Posts that did numbers compared to others.", color = "red", icon = "fire" },
  { name = "Test", description = "Categories can be set and customized entirely from config, woo-hoo!", color = "green", icon = "feather" },
]

# Accent color used by Ametrine.
#
# Has several modes:
# - Use one of the presets (applies to both light and dark modes):
#   accent_color = "<red, orange, yellow, green, blue, purple>"
# - Use a single HSL color for both light and dark modes:
#   accent_color = "hsl(270, 50%, 60%)"
# - Use separate colors for light and dark modes (it's possible to mix both
# presets and HSL colors):
#   Presets:    accent_color = ["red", "blue"]
#   Preset + HSL:   accent_color = ["red", "hsl(270, 50%, 60%)"]
#   HSLs: accent_color = ["hsl(270, 50%, 60%)", "hsl(27.567572, 87%, 67%)"]
#
# Custom colors must be in HSL format. You can also define your own color
# presets by creating an "accent_presets.toml" file under the "./data/"
# directory with custom preset names and colors. Use the one located in Ametrine
# as a reference.
# accent_color = "hsl(40, 73%, 49%)"
accent_color = "orange"
# "Additional CSS styles; expects them to be in the "./static/" directory."
# "If you are using Sass these will be generated there automatically."

# ... or does it?
# Mambuco's config (mambuco.dev) sources sass from /sass folder,
# so by doing that way, it compiles all of them into "styles.css"
# and puts it next to /public/index.html, thus actually doing shit.
# LETSGOOOOOOOO-
styles = ["index.css"]

# Additional JavaScript scripts; expects them to be in the "./static/"
# directory.
#
# scripts = ["a.js", "b.js"]

# Path to the page that is being considered "Home", e.g. for the "Go Home"
# button on 404.
# home_url = "@/home/index.md"
# Should be left default unless you have doing, uhh, experiements with your home page :)
# You can use @ to refer to the content directory directly.
# (e.g. "@/blog/page.md" instead of "[project root]/content/blog/page.md")
# home_url = "@/home/index.md"

# URL to website's source code.
source_url = "https://github.com/backups1der/blog"
# ...and to it's bug tracker/issues page.
issues_url = "https://github.com/backups1der/blog/issues/new"

# Whether to show estimated read time in posts.
show_reading_time = true

# Ultimate skid³ prevention toggle. Set this value "false" to enable :)
# Works by making skid³'s use more ATP's to select and hit
# ctrl + c as opposed to just clicking on a button.
copy_button = true

# Whether to show an audio play button for audio files embedded using the audio shortcode
audio_button = true

# Custom separator used throughout the theme.
separator = "***"
# Custom separator used in website's title and article metadata.
title_separator = "|"

# Locale and timezone shit.
date_format = "%d %B %Y"
date_format_long = "%d %B %Y, %R (%Z)"
date_locale = "tr_TR"
timezone = "Europe/Istanbul"

# Shows a QR code that directly jumps to your Mastodon instance, focused on comment writer.
show_comments_qr = true

# Whether to use Content Security Policy.
# Keep in mind that although this can potentially increase security,
# it can break some things, in which case you will need to set a custom policy.
# csp = [
#     { directive = "img-src", domains = [
#         "'self'",
#         "https:",
#         "data:",
#     ] },
#     { directive = "media-src", domains = [
#         "'self'",
#         "https:",
#     ] },
#     { directive = "script-src", domains = [
#         "cloud.umami.is",
#         "ntfy.anins1der.com",
#     ] },
#     { directive = "style-src", domains = [
#         "'self'",
#         "'unsafe-inline'",
#     ] },
#     { directive = "frame-src", domains = [
#         "https://player.vimeo.com",
#         "https://sitwatch.net",
#         "https://www.youtube-nocookie.com",
#         "https://vmst.io",
#     ] },
#     { directive = "connect-src", domains = [
#         "api.lanyard.rest",
#         "discord.com",
#         "*.umami.dev",
#         "cloud.umami.is",
#     ] },
#     { directive = "base-uri", domains = [
#         "'none'",
#     ] },
#     { directive = "form-action", domains = [
#         "'none'",
#     ] },
# ]

[extra.meta]
# Variables bellow accept either "true" or a filename.
# Favicon can also accept an emoji instead of a filename.
# File extension are being respected, so e.g. if favicon has .gif extension
# it'll be treated as an animated one.
# If set to "true" these will use the default filenames:
# favicon          = favicon.png
# apple_touch_icon = apple-touch-icon.png
# card             = card.png
favicon = "dowg.png"
apple_touch_icon = "dowg.png"
card = true
# card = "card.png"

[extra.nav]
# When set to true and [extra.fediverse] is defined, it will use avatar from
# said Mastodon account, otherwise it'll fallback to apple_touch_icon specified
# in [extra.meta] or its default value.
# Also accepts arbitrary filenames and URLs for custom images.
# icon = "apple-touch-icon.webp"
icon = "dowg.png"
# Usage of an icon is heavily adviced. In case if none is provided, first two
# letters of the link name will be used instead.
# Any icon name from https://phosphoricons.com can be used.
links = [
    { url = "@/blog/_index.md", name = "Blog", icon = "newspaper" },
    { url = "@/about/_index.md", name = "About me", icon = "user" },
]

[extra.footer]
# Set to false to disable copyright text, or set to anything else to use it as
# the copyright text (Markdown supported).
# $YEAR will be replaced with current year.
copyright = "<span class=center>© **anins1der**, $YEAR.</span>\nI am designed to not give a fuck about stuff that I don't really care, so I don't give a fuck about my rights being \"rEsErVeD\" or some shit like that.\nIf you want an license then just check [The Unlicense Page](/licence) <span class=spoiler>that is SECRETT!! OOOOO--</span>"

# Whether to show "Powered by Zola and Ametrine", and a link to the source code
show_powered_by = true
show_source = true
# Whether to show timestamp of the last build. Uses UTC timezone unless your own
# is set under extra.timezone. If Git repository is detected, current commit
# hash will be appended.
show_timestamp = true
# Social links in the footer.
# Any icon name from https://simpleicons.org can be used.
socials = [
  { url = "https://snugnook.org", icon = "cat" },
]
# List of webrings. Allowed fields:
# - name     (required)
# - url      (required)
# - previous (required)
# - next     (required)
# - random   (optional)
# "$HOST" can be used to insert config.base_url with "https://" stripped away.
webrings = [
  { name = "Snug Ring", url = "https://snugnook.org/ring", previous = "https://snugnook.org/ring/$HOST/previous", next = "https://snugnook.org/ring/$HOST/next", random = "https://snugnook.org/ring/random" },
]

# [extra.fediverse]
# Fediverse integration.
# Used for:
# - Commenting
# - Custom emoji shortcode
# - Website verification
# - Author attribution
#
# Mastodon-powered commenting is based on
# https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/
#
# Values can be overridden in the front-matter, e.g.
# for multi-author blogs or guest posts.

# host = "indieweb.social"
# user = "anins1der"

# [extra.analytics]
# Specify which analytics service you want to use.
# Supported options: "goatcounter", "umami", and "plausible".
# service = "umami"

# Unique identifier for tracking.
# For GoatCounter, this is the code you choose during signup.
# For Umami, this is the website ID.
# For Plausible, this is the domain name (e.g. "example.com").
# Note: Leave this field empty if you're self-hosting GoatCounter.
# id = "61ac1043-f048-4aee-8eac-28a553cad810"

# Optional: Specify the URL for self-hosted analytics instances.
# For GoatCounter: Base URL like "https://stats.example.com"
# For Umami: Base URL like "https://umami.example.com"
# For Plausible: Base URL like "https://plausible.example.com"
# Leave this field empty if you're using the service's default hosting.
# self_hosted_url = "https://stats.daudix.one"

# Optional: For Umami, enable this option if you don't want to collect search
# parameters from the URL.
# exclude_search = false

# Optional: For Umami, enable this option if you don't want to collect the hash
# value from the URL.
# exclude_hash = false

# Optional: For Umami, enable this option to respect users' Do Not Track (DNT)
# settings.
# do_not_track = true

[extra.debug]
# Display outlines around all elements
# layout = true
# Don't load any styles for
# no_styles = true

# Skip loading of Mastodon emojis used via the emoji.html shortcode.
# Sometimes needed for building the project because this shortcode can also pull emojis
# from Mastodon instances, and it fails when you don't set up your credentials properly.
no_emojis = true