name: Build Zola project and deploy to "public" branch

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Zola
        run: apt install zola

      - name: Build site
        run: zola build

      - name: Push to "public" branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: public
          force_orphan: true